import { headquartersRepositories, type Product } from "@/repositories";
import styles from "./Products.module.css";
const productsRepository = headquartersRepositories.products;
const products = productsRepository.getProducts();
const featuredProduct = productsRepository.getFeaturedProduct() ?? products[0];
const laboratoryPipeline = productsRepository.getLaboratoryPipeline();
const productStatus = productsRepository.getProductStatus();

function Station({ station }: { station: Product }) { return <article className={`${styles.station} ${station.featured ? styles.featured : ""}`}><div className={styles.stationTop}><span>{station.designation}</span><span className={styles.status}>{station.status}</span></div><div className={styles.stationBody}><div className={styles.stationDiagram} aria-hidden="true"><i /><i /><i /></div><h3>{station.name}</h3><p>{station.description}</p><ul>{station.modules?.map((module) => <li key={module}>{module}</li>)}</ul><a href={station.href} className={styles.link}>{station.action}<span aria-hidden="true">→</span><span className="sr-only">: {station.name}</span></a></div></article>; }
export function Products() { return <section id="products" className={`${styles.section} section-space`} aria-labelledby="products-title"><div className="container-shell"><header className={styles.identity}><div><p className={styles.eyebrow}>FLOOR 02 / PRODUCTS LABORATORY</p><h2 id="products-title">Systems under construction.</h2></div><div className={styles.meta}><span><i /> {productStatus.productHealth}</span><p>{productStatus.totalProducts} systems / {productStatus.releaseReadiness}% internal release readiness.</p></div></header><div className={styles.labGrid}><Station station={featuredProduct} /><div className={styles.secondary}>{products.filter((station) => station !== featuredProduct).map((station) => <Station key={station.name} station={station} />)}</div></div><section className={styles.pipeline} aria-labelledby="pipeline-title"><div><p className={styles.eyebrow}>LABORATORY PIPELINE</p><h3 id="pipeline-title">From question to working system.</h3><p className={styles.pipelineMeta}>{productStatus.pipelineStageCount} stages / {productStatus.pipelineProgress}% progress / {productStatus.generatedAt}</p></div><ol>{laboratoryPipeline.map((stage, index) => <li key={stage}><span>{String(index + 1).padStart(2, "0")}</span><b>{stage}</b></li>)}</ol></section></div></section>; }
