import { headquartersRepositories } from "@/repositories";
import styles from "./ResearchLabs.module.css";

const researchRepository = headquartersRepositories.research;
const programs = researchRepository.getPrograms();
const protocols = researchRepository.getProtocols();
const researchStatus = researchRepository.getResearchStatus();

export function ResearchLabs() {
  return <section id="research" className={`${styles.section} section-space`} aria-labelledby="research-title"><div className="container-shell"><header className={styles.identity}><div><p className={styles.eyebrow}>FLOOR 04 / RESEARCH LABS</p><h2 id="research-title">Questions worth engineering.</h2></div><div className={styles.meta}><span><i /> Experimental classification</span><p>Researching future interfaces, autonomous intelligence, and AI-native computing systems.</p></div></header><div className={styles.labLayout}><article className={styles.experiment} aria-labelledby="experiment-title"><div className={styles.panelTop}><span>CHAMBER / EXP-01</span><strong>{researchStatus.researchHealth.toUpperCase()}</strong></div><div className={styles.chamber}><div className={styles.signal}><span /><span /><span /></div><h3 id="experiment-title">{researchStatus.primaryExperiment}</h3><p>A research system exploring how JARVIS may understand code, voice, screen context, visual input, active applications, and engineering missions.</p><div className={styles.layers} aria-label="Multimodal JARVIS experimental architecture"><div>INPUT SYSTEMS</div><i /><div>PERCEPTION LAYER</div><i /><div>REASONING CORE</div><i /><div>MISSION ENGINE</div><i /><div>ACTION LAYER</div></div><p className={styles.disclaimer}>Research architecture. {researchStatus.experimentalRatio}% experimental / {researchStatus.protocolCount} protocols.</p></div></article><section className={styles.programs} aria-labelledby="programs-title"><div className={styles.panelTop}><span id="programs-title">RESEARCH PROGRAMS</span><span>{researchStatus.totalPrograms} PROGRAMS / {researchStatus.headquartersResearchReadiness}% READY</span></div>{programs.map(([id, title, description, status]) => <article className={styles.program} key={id}><span className={styles.programId}>{id}</span><div><h3>{title}</h3><p>{description}</p><strong>{status}</strong></div></article>)}</section></div><section className={styles.protocols} aria-labelledby="protocols-title"><div><p className={styles.eyebrow}>LABORATORY PROTOCOLS</p><h3 id="protocols-title">Research with control.</h3></div><ul>{protocols.map((protocol, index) => <li key={protocol}><span>{String(index + 1).padStart(2, "0")}</span>{protocol}</li>)}</ul></section></div></section>;
}
