import { headquartersCapabilities } from "@/capabilities";
import type { DepartmentLookup } from "@/capabilities";
import type { JarvisGuideMessage, JarvisGuideTopic } from "./contracts";

export class HeadquartersGuideService {
  constructor(private readonly capabilities = headquartersCapabilities) {}

  getWelcomeGuide(): JarvisGuideMessage { const status = this.capabilities.getEngineeringHealth(); return this.message("welcome", "Headquarters online", `Welcome to NightCode Headquarters. All operational divisions are available; current headquarters status is ${status.toLowerCase()}.`, status, "Headquarters", "View headquarters summary", "command"); }
  getHeadquartersSummaryGuide(): JarvisGuideMessage { const summary = this.capabilities.getHeadquartersSummary(); return this.message("headquarters-summary", "Headquarters summary", `${summary.featuredProduct} is the featured product, ${summary.featuredMission} is the featured mission, and ${summary.primaryResearch} is the primary research program.`, summary.engineeringHealth, "NightCode Headquarters", "Open Command Center", "command", summary.generatedAt); }
  getDepartmentGuide(department: string): JarvisGuideMessage { const result = this.capabilities.findDepartment(department); if (!result.found) return this.message("unknown", "Department not found", `No Headquarters department is assigned to “${department}”.`, undefined, undefined, undefined, undefined); const topic = this.topicForDepartment(result.name); const content = this.departmentMessage(topic, result); return this.message(topic, result.name, content, result.status, result.name, "Open department", this.sectionForTopic(topic)); }
  getFeaturedProductGuide(): JarvisGuideMessage { const product = this.capabilities.getFeaturedProduct(); return product ? this.message("featured-product", product.name, `${product.name} is the featured product station: ${product.description}`, product.status, "Products Laboratory", "Open Products Laboratory", "products") : this.message("featured-product", "No featured product", "No featured product is currently assigned in the Products Laboratory.", undefined, "Products Laboratory"); }
  getFeaturedMissionGuide(): JarvisGuideMessage { const mission = this.capabilities.getFeaturedMission(); return mission && mission !== "None" ? this.message("featured-mission", mission, `${mission} is the current featured strategic mission.`, undefined, "Mission Control", "Open Mission Control", "roadmap") : this.message("featured-mission", "No featured mission", "No featured mission is currently active.", undefined, "Mission Control"); }
  getPrimaryResearchGuide(): JarvisGuideMessage { const research = this.capabilities.getPrimaryResearch(); return research && research !== "None" ? this.message("primary-research", research, `${research} is the designated primary research experiment in Research Labs.`, this.capabilities.getResearchOverview().researchHealth, "Research Labs", "Open Research Labs", "research") : this.message("primary-research", "No primary research", "No primary research program is currently designated.", undefined, "Research Labs"); }
  getEngineeringHealthGuide(): JarvisGuideMessage { const health = this.capabilities.getEngineeringHealth(); return this.message("engineering-health", "Engineering status", `Engineering Division is currently ${health.toLowerCase()}.`, health, "Engineering Division", "Open Engineering Division", "engineering-division"); }
  getGuideForTopic(topic: JarvisGuideTopic): JarvisGuideMessage { switch (topic) { case "welcome": return this.getWelcomeGuide(); case "headquarters-summary": return this.getHeadquartersSummaryGuide(); case "engineering": return this.getDepartmentGuide("Engineering Division"); case "products": return this.getDepartmentGuide("Products Laboratory"); case "mission-control": return this.getDepartmentGuide("Mission Control"); case "research": return this.getDepartmentGuide("Research Labs"); case "command-center": return this.getDepartmentGuide("Command Center"); case "featured-product": return this.getFeaturedProductGuide(); case "featured-mission": return this.getFeaturedMissionGuide(); case "primary-research": return this.getPrimaryResearchGuide(); case "engineering-health": return this.getEngineeringHealthGuide(); case "unknown": return this.message("unknown", "Request not recognized", "I don't recognize that Headquarters request."); } }

  private message(topic: JarvisGuideTopic, title: string, message: string, status?: string, department?: string, actionLabel?: string, targetSectionId?: string, generatedAt = this.capabilities.getEngineeringOverview().generatedAt): JarvisGuideMessage { return Object.freeze({ id: `jarvis-${topic}`, topic, title, message, ...(status ? { status } : {}), ...(department ? { department } : {}), ...(actionLabel && targetSectionId ? { actionLabel, targetSectionId } : {}), generatedAt }); }
  private topicForDepartment(department: string): JarvisGuideTopic { const value = department.toLowerCase(); return value.includes("engineering") ? "engineering" : value.includes("products") ? "products" : value.includes("mission") ? "mission-control" : value.includes("research") ? "research" : value.includes("command") ? "command-center" : "unknown"; }
  private sectionForTopic(topic: JarvisGuideTopic): string | undefined { return topic === "engineering" ? "engineering-division" : topic === "products" ? "products" : topic === "mission-control" ? "roadmap" : topic === "research" ? "research" : topic === "command-center" ? "command" : undefined; }
  private departmentMessage(topic: JarvisGuideTopic, result: Extract<DepartmentLookup, { found: true }>): string { switch (topic) { case "engineering": return `Engineering Division is ${result.status.toLowerCase()}, where NightCode turns systems into working software.`; case "products": return `Products Laboratory is ${result.status.toLowerCase()}, coordinating active systems and the development pipeline.`; case "mission-control": return `Mission Control is ${result.status.toLowerCase()}, tracking strategic directives and development priorities.`; case "research": return `Research Labs is ${result.status.toLowerCase()}, containing experimental systems and long-term programs.`; case "command-center": return `Command Center is ${result.status.toLowerCase()}, the Headquarters access point for choosing a direction.`; default: return `${result.name} is currently ${result.status.toLowerCase()}.`; } }
}
