import type { TerrainProfile } from "../core/TerrainTypes";

export const eagleSummitProfile = {
  id: "eagle-summit-v1",
  name: "Eagle Summit Island",
  seed: 731942,
  worldScale: 68,
  resolution: 160,
  origin: [0, -3.4, -3],
  coastline: {
    radius: [30, 27],
    edgeWidth: 0.22,
    asymmetry: 0.09,
    cliffStrength: 0.86,
    beachElevation: 0.14,
  },
  heightProfile: {
    oceanLevel: 0,
    baseElevation: 1.55,
    noiseAmplitude: 0.75,
    noiseFrequency: 0.075,
    erosionStrength: 0.28,
    maxElevation: 11,
  },
  mountains: [
    {
      id: "observatory-peak",
      kind: "peak",
      center: [9, -17],
      radius: [8.5, 9.5],
      elevation: 10.6,
      rotation: -0.22,
      strength: 0.96,
      falloff: "gaussian",
    },
    {
      id: "evergreen-ridge",
      kind: "ridge",
      center: [-13, -7],
      radius: [6, 13],
      elevation: 6.7,
      rotation: 0.38,
      strength: 0.82,
      falloff: "smooth",
    },
    {
      id: "innovation-ridge",
      kind: "ridge",
      center: [14, -1],
      radius: [5.5, 11],
      elevation: 5.6,
      rotation: -0.34,
      strength: 0.78,
      falloff: "smooth",
    },
  ],
  plateaus: [
    {
      id: "research-valley-basin",
      kind: "plateau",
      center: [0, -11],
      radius: [8.5, 7],
      elevation: 7.5,
      rotation: 0.08,
      strength: 0.76,
      falloff: "smooth",
    },
    {
      id: "headquarters-plateau",
      kind: "plateau",
      center: [0, 4],
      radius: [10.5, 8],
      elevation: 4.25,
      rotation: -0.08,
      strength: 0.9,
      falloff: "smooth",
    },
    {
      id: "coastal-plain",
      kind: "plain",
      center: [3, 19],
      radius: [13, 7],
      elevation: 1.25,
      strength: 0.88,
      falloff: "smooth",
    },
    {
      id: "west-expansion",
      kind: "plateau",
      center: [-18, 8],
      radius: [6.5, 7],
      elevation: 3.2,
      rotation: 0.2,
      strength: 0.72,
      falloff: "smooth",
    },
  ],
  valleys: [
    {
      id: "research-valley",
      kind: "valley",
      center: [1, -10],
      radius: [4.5, 8],
      elevation: 7.15,
      rotation: 0.04,
      strength: 0.52,
      falloff: "gaussian",
    },
    {
      id: "river-valley",
      kind: "valley",
      center: [-6, 11],
      radius: [5.5, 13],
      elevation: 2.15,
      rotation: -0.15,
      strength: 0.9,
      falloff: "smooth",
    },
  ],
  futureRiverPaths: [
    {
      id: "summit-river-reservation",
      points: [
        [2, -8],
        [-1, -2],
        [-4, 6],
        [-7, 13],
        [-5, 24],
      ],
      width: 1.4,
    },
  ],
  futureBiomeMasks: [
    {
      id: "evergreen-biome",
      biome: "temperate-evergreen",
      center: [-13, -7],
      radius: [9, 14],
    },
    {
      id: "coastal-biome",
      biome: "coastal-grassland",
      center: [3, 18],
      radius: [14, 8],
    },
  ],
  reservedZones: [
    {
      id: "headquarters-zone",
      purpose: "Future Headquarters campus",
      center: [0, 4],
      radius: [8, 5.5],
    },
    {
      id: "observatory-zone",
      purpose: "Future observatory",
      center: [9, -17],
      radius: [3, 3],
    },
    {
      id: "innovation-zone",
      purpose: "Future innovation district",
      center: [14, -1],
      radius: [4.5, 6],
    },
    {
      id: "west-expansion-zone",
      purpose: "Unassigned long-term expansion",
      center: [-18, 8],
      radius: [5, 5],
    },
  ],
  viewpoints: [
    {
      id: "overview",
      label: "Island Overview",
      position: [42, 34, 48],
      target: [0, 2.5, 0],
    },
    {
      id: "observatory",
      label: "Observatory",
      position: [17, 15, -25],
      target: [9, 8, -17],
    },
    {
      id: "headquarters",
      label: "Headquarters Plateau",
      position: [17, 11, 21],
      target: [0, 4.2, 4],
    },
    {
      id: "harbor",
      label: "Harbor Approach",
      position: [5, 7, 38],
      target: [1, 2.5, 8],
    },
    {
      id: "coastline",
      label: "Rocky Coastline",
      position: [-31, 8, 22],
      target: [-19, 1, 10],
    },
    {
      id: "innovation",
      label: "Innovation Ridge",
      position: [27, 12, 6],
      target: [14, 5, -1],
    },
    {
      id: "performance",
      label: "Performance",
      position: [0, 48, 2],
      target: [0, 0, 0],
    },
  ],
} as const satisfies TerrainProfile;
